name: RDP
on: workflow_dispatch
jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 360
    steps:
    - name: Tailscale
      uses: tailscale/github-action@v3
      with:
        authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
        hostname: rdp-pc
    - name: Ativar RDP
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "Kaue@123" -Force)
        Write-Host "=== RDP PRONTO ==="
        Write-Host "Login: runneradmin"
        Write-Host "Senha: Kaue@123"
        $ip = (Get-NetIPAddress -AddressFamily IPv4 | Where-Object { $_.IPAddress -like "100.*" }).IPAddress
        Write-Host "IP Tailscale: $ip"
    - name: Manter ligado
      run: |
        while($true){ Write-Host "Rodando... $(Get-Date)"; Start-Sleep 300 }
